---
abstract: 'An implementation of Promises in Perl'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  AnyEvent: 0
  Test::Fatal: 0
  Test::More: 0.89
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Promises
requires:
  Carp: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  constant: 0
  strict: 0
  warnings: 0
version: 0.03
x_authority: cpan:STEVAN
