---
abstract: 'An implementation of Promises in Perl'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  AnyEvent: 0
  Test::Fatal: 0
  Test::More: 0.89
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Promises
requires:
  AE: 0
  AnyEvent: 0
  Carp: 0
  EV: 0
  Module::Runtime: 0
  Mojo::IOLoop: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  constant: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/stevan/promises-perl.git
version: 0.91
x_authority: cpan:STEVAN
